### Numpy:Arrays

1) Różnice listy vs tablice

In [151]:
import numpy as np

In [152]:
#deklaracja listy
listA = [1,2,3]
#deklaracja tablicy i przypisanie do niej listy
array=np.array(listA)

In [153]:
#Sprawdzenie, jakiego typu jest zmienna
type(listA)

list

In [154]:
type(array)

numpy.ndarray

In [155]:
#tablica zawierajaca 10 elementow
np.array(range(0,10))

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [156]:
#skrocona wersja powyzszego zapisu
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

2) Tablice dwuwymiarowe w Numpy, macierze


In [157]:
#lista dwuwymiarowa
ListB = [[1,2,3],[2,3,4]]
# przypisanie do tablicy
Matrix=np.array(ListB)

In [158]:
print("Tablica dwuwymiarowa: \n",Matrix)

Tablica dwuwymiarowa: 
 [[1 2 3]
 [2 3 4]]


In [159]:
#tworzenie macierzy z dowolna iloscia elementow, rzedow i kolumn
# tablica zawierajaca 30 elementow od 1 do 30 typu float
makeMatrix=np.linspace(1,30,30)

In [160]:
makeMatrix

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.,
       14., 15., 16., 17., 18., 19., 20., 21., 22., 23., 24., 25., 26.,
       27., 28., 29., 30.])

In [161]:
#ustawianie liczby 3 rzedow i 10 kolumn
twoD=makeMatrix.reshape(3,10)
print(twoD.shape)

(3, 10)


In [162]:
twoD

array([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.],
       [11., 12., 13., 14., 15., 16., 17., 18., 19., 20.],
       [21., 22., 23., 24., 25., 26., 27., 28., 29., 30.]])

In [163]:
#wyciaganie konkretnych danych z macierzy
#chce wyciagnac 3, 16, 21
first=twoD[0,2]
second=twoD[1,5]
third=twoD[2,0]

In [164]:
print(first, second, third)

3.0 16.0 21.0


In [165]:
#wyciaganie konkretnych rzedow i kolumn
allRowsThirdFourthFifthColumns=twoD[0:3,2:5]

In [166]:
print(allRowsThirdFourthFifthColumns)

[[ 3.  4.  5.]
 [13. 14. 15.]
 [23. 24. 25.]]


3) Wprowadzanie danych do tablicy

In [167]:
#zastapienie wartosci nowa w macierzy o wskazanych koordynatach
twoD[2,0]=100

In [168]:
twoD

array([[  1.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.,  10.],
       [ 11.,  12.,  13.,  14.,  15.,  16.,  17.,  18.,  19.,  20.],
       [100.,  22.,  23.,  24.,  25.,  26.,  27.,  28.,  29.,  30.]])

In [169]:
#przypisanie do 5 pierwszych elementow nowej wartosci za pomoca nowej tablicy
twoD2=twoD[0:1,0:5]

In [170]:
twoD2

array([[1., 2., 3., 4., 5.]])

In [171]:
twoD2[:]=50

In [172]:
twoD2

array([[50., 50., 50., 50., 50.]])

In [173]:
#Powyzszy zapis spowoduje nadpisanie wartosci rowniez w pierwotnej tablicy
twoD

array([[ 50.,  50.,  50.,  50.,  50.,   6.,   7.,   8.,   9.,  10.],
       [ 11.,  12.,  13.,  14.,  15.,  16.,  17.,  18.,  19.,  20.],
       [100.,  22.,  23.,  24.,  25.,  26.,  27.,  28.,  29.,  30.]])

In [179]:
#stosowanie funkcji copy() zapobiega nadpisywaniu danych
twoD3= twoD2.copy()

In [180]:
twoD3

array([[50., 50., 50., 50., 50.]])

In [181]:
twoD3[:]=15

In [182]:
twoD3

array([[15., 15., 15., 15., 15.]])

In [183]:
twoD2

array([[50., 50., 50., 50., 50.]])

In [184]:
twoD

array([[ 50.,  50.,  50.,  50.,  50.,   6.,   7.,   8.,   9.,  10.],
       [ 11.,  12.,  13.,  14.,  15.,  16.,  17.,  18.,  19.,  20.],
       [100.,  22.,  23.,  24.,  25.,  26.,  27.,  28.,  29.,  30.]])